config/routes.rb
Rails.application.routes.draw do
  resources :estates 

  post 'home', to: 'estates#home'

  post 'search', to: 'estates#search'

  devise_for :users

  root 'estates#home'
  post 'new_estate', to: 'estates#new'

end

app/models/estate.rb
class Estate < ActiveRecord::Base
  belongs_to :user
#  acts_as_geolocated lat: 'latitude', lng: 'longitude'
  acts_as_geolocated
  has_one :location
  has_many :pictures, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :pictures
  

#  scope :within_radius, lambda {|latitude, longitude, metres| where("earth_box(ll_to_earth(?, ?), ?) @> ll_to_earth(latitude, longitude)", latitude, longitude, metres) }

end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  before_action :set_estate, only: [:show, :edit, :update, :destroy,]
  before_filter :authenticate_user!, :only => [:index, :new, :home]
  # GET /estates
  # GET /estates.json
  def index
    @page = 'index_page'
#    @estates = Estate.paginate(:page => params[:page], :per_page => 4)




#  binding.pry
#  @page = params[:req_page]

 
  @page = params[:req_page]
    if params[:address].present?
      @page = 'search'
  puts    @ptype = params[:select]
      results = Geocoder.search(params[:address])
      if results[0].present?
        puts @res_address = results[0].formatted_address;
        @plat = params[:p_lat];
        @plng = params[:p_lng]; 
#        params[:welcome][:address]
        mr = 10 ;
        radius = mr*1000;
        @estates =  Estate.within_radius(radius, @plat, @plng).order_by_distance(@plat, @plng).where(ptype:@ptype).paginate(:page => params[:page], :per_page => 4) unless @ptype == 'all_prop'
        @estates =  Estate.within_radius(radius, @plat, @plng).order_by_distance(@plat, @plng).paginate(:page => params[:page], :per_page => 4) if @ptype == 'all_prop'
        
        if @estates.size > 1
          puts @res = "#{@estates.size} results found in #{@res_address} "
        else
          puts @res = "#{@estates.size} result found in #{params[:address]} "
        end
      else
        @estates = Estate.paginate(:page => params[:page], :per_page => 4)  
      end
    else
        @estates = Estate.paginate(:page => params[:page], :per_page => 4)
        @res ="listing all property"
    end



  end



  # GET /estates/1
  # GET /estates/1.json
  def home
      @page = 'home_page'
      @rem_ip = remote_ipp
      puts @rem_ip
      puts @location = Geocoder.search("#{@rem_ip}")
      if @location[0].present? && @location[0].latitude.present?
        mr = 20 ;
        radius = mr*1000;
        @estates =  Estate.within_radius(radius,@location[0].latitude,@location[0].longitude).order_by_distance(@location[0].latitude,@location[0].longitude)

      else
        @estates = Estate.all  
      end

     @estates.each do |st| 
      puts st.address
     end 

      @res = '';
      @back_url = session[:my_previous_url]
  end
 
  def search
  puts params
  @page = params[:req_page]
    if params[:address].present?
  puts    @ptype = params[:select]
      results = Geocoder.search(params[:address])
      if results[0].present?
        puts @res_address = results[0].formatted_address;
        @plat = params[:p_lat];
        @plng = params[:p_lng]; 
#        params[:welcome][:address]
        mr = 10 ;
        radius = mr*1000;
        @estates =  Estate.within_radius(radius, @plat, @plng).order_by_distance(@plat, @plng).where(ptype:@ptype).paginate(:page => params[:page], :per_page => 100) unless @ptype == 'all_prop'
        @estates =  Estate.within_radius(radius, @plat, @plng).order_by_distance(@plat, @plng).paginate(:page => params[:page], :per_page => 100) if @ptype == 'all_prop'
        
        if @estates.size > 1
          puts @res = "#{@estates.size} results found in #{@res_address} "
        else
          puts @res = "#{@estates.size} result found in #{params[:address]} "
        end
      else
        @estates = Estate.all  
      end
    else
        @estates = Estate.all
        @res ="please select valid city"
    end

    render 'home'

  end




  def show
  
    @pictures = @estate.pictures.all
    @back_url = session[:my_previous_url]
  end



  # GET /estates/new
  def new
    @estate = current_user.estates.build
    @picture = @estate.pictures.build
    @rem_ip = remote_ipp
    puts @location = Geocoder.search("#{@rem_ip}")
puts    @c_lat = @location[0].latitude if @location[0].present?
puts    @c_lng = @location[0].longitude if @location[0].present?
    @back_url = session[:my_previous_url]
  end

  # GET /estates/1/edit
  def edit
    @type = @estate.ptype
    @back_url = session[:my_previous_url]
  end

  # POST /estates
  # POST /estates.json
  def create
    @back_url = session[:my_previous_url]
    @estate = current_user.estates.new(estate_params)
        respond_to do |format|
      if @estate.save
         params[:pictures]['avatar'].each do |a|
          @picture = @estate.pictures.create!(:avatar => a)
       end
        format.html { redirect_to estate_path(@estate), 'data-no-turbolink' => true , notice: 'your property was successfully posted.' }
        format.json { render :show, status: :created, location: @estate }
      else
        format.html { render :new }
        format.json { render json: @estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estates/1
  # PATCH/PUT /estates/1.json
  def update
    @back_url = session[:my_previous_url]
    respond_to do |format|
      if @estate.update(estate_params)
        if @estate.pictures.present?
      @estate.pictures.each do |pic|
        pic.destroy
      end
    end

        params[:pictures]['avatar'].each do |a|
          @picture = @estate.pictures.create(:avatar => a)
          
       end
        format.html { redirect_to @estate, notice: 'property detail updated.' }
        format.json { render :show, status: :ok, location: @estate }
      else
        format.html { render :edit }
        format.json { render json: @estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estates/1
  # DELETE /estates/1.json
  def destroy
    @back_url = session[:my_previous_url]
    @estate.destroy
    respond_to do |format|
      format.html { redirect_to action: 'index', notice: 'Estate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  def remote_ipp
    if request.remote_ip.nil? || request.remote_ip == '127.0.0.1'
     '103.9.12.150'
    else
     request.remote_ip
    end
  end
 
  
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estate
      @estate = Estate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estate_params
      params.require(:estate).permit(:ptype, :stype, :levels, :area, :bedroom, :hall, :bathroom, :built, :feature, :price, :user_id, :address, :latitude, :longitude, :avatar)
    end

end

app/helpers/estates_helper.rb
module EstatesHelper
end

app/views/estates/_appartment.html.erb
<h1>Appartment</h1>
<%= form_for(@estate, :html => { :multipart => true }) do |f| %>
  <% if @estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
      <% @estate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.hidden_field :ptype, :value => 'appartment' %>  
  </div>

 
  <div class="field">
    <%= f.label :For %>
    <%= f.select :stype, [['Sell','sell'],['Rent','rent']] %></div>

  <div class="field">
    <%= f.label :area %><br>
    <%= f.number_field :area, min:'0', :required => true %>
  </div>

  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.number_field :bedroom, min:'0', :required => true %>
  </div>

  <div class="field">
    <%= f.label :hall %><br>
    <%= f.number_field :hall, min:'0', :required => true %>
  </div>
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.number_field :bathroom, min:'0', :required => true  %>
  </div>

  <div class="field">
    <%= f.label :"built in" %><br>
    <%= f.date_select :built, :required => true  %>
  </div>

  <div class="field">
    <%= f.label :"Description about Appartment" %><br>
    <%= f.text_field :feature %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, min:'0', :required => true %>
  </div>



   <%= render :partial => "mapshow", :locals=>{:f=>f} %>


  <div class="actions">
    <%= f.submit :'Submit' %>
  </div>
<% end %>

app/views/estates/_flat.html.erb
<h1>Flat</h1>
<%= form_for(@estate, :html => { :multipart => true }) do |f| %>
  <% if @estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
      <% @estate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
  <%= f.hidden_field :ptype, :value => 'flat' %>  
  </div>



  <div class="field">
    <%= f.label :For %>
    <%= f.select :stype, [['Sell','sell'],['Rent','rent']] %></div>

  
  <div class="field">
    <%= f.label :area %><br>
    <%= f.number_field :area, min:'0', :required => true %>
  </div>
  
  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.number_field :bedroom, min:'0', :required => true %>
  </div>
  
  <div class="field">
    <%= f.label :hall %><br>
    <%= f.number_field :hall, min:'0', :required => true %>
  </div>
  
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.number_field :bathroom, min:'0', :required => true %>
  </div>
  
  <div class="field">
    <%= f.label :built %><br>
    <%= f.date_select :built, :required => true %>
  </div>
  
  <div class="field">
    <%= f.label :"Description about flat" %><br>
    <%= f.text_field :feature %>
  </div>
  
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, min:'0', :required => true %>
  </div>


   <%= render :partial => "mapshow", :locals=>{:f=>f} %>

  
  <div class="actions">
    <%= f.submit :'Submit' %>
  </div>

<% end %>

app/views/estates/_indexSearch.html.erb
    <div class="psearch">
      Search
      <%= form_for '', url: 'estates', method: :get  do |f| %>
        
        <%= f.select :select, [['All','all_prop'],['Villa','villa'],['Flat','flat'],['Appartment','appartment'],['Land','land']], :class=>'sfield' %>
        <br>  

        <%= f.text_field :address, :class=>'sfield', :id=>'autocomplete',:placeholder=>'Enter city name' %>
        
        <%= f.hidden_field :req_page, :value => @page %>
        <%= f.hidden_field :p_lat, :value =>'' ,id: 'cityLat' %>
        <%= f.hidden_field :p_lng, :value =>'' ,id: 'cityLng' %>
        <br>
        <%= f.submit :'Search', class:'sfield', id:'s_submit',:disabled => true %>
        <% end %>
        <% if @res.present? %>
        <div><%= @res  %></div>
        <% end %>

        
    </div>

<script>
// for address auto complete
var placeSearch, autocomplete;

function enablesubmit(){
//  alert("text")

  $('#s_submit').prop('disabled', false);
}

function initializ() {
  autocomplete = new google.maps.places.Autocomplete(
      /** @type {HTMLInputElement} */(document.getElementById('autocomplete')),
      { types: ['geocode'] });
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
//    document.getElementById(s_submit).disabled = enabled;
  var place = autocomplete.getPlace();
  document.getElementById('cityLat').value = place.geometry.location.lat();
  document.getElementById('cityLng').value = place.geometry.location.lng();
 
  enablesubmit();  

  });
}

google.maps.event.addDomListener(window, 'load', initializ);


 </script>

app/views/estates/_land.html.erb
<h1>Land</h1>
<%= form_for(@estate, :html => { :multipart => true }) do |f| %>
  <% if @estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
      <% @estate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :ptype, :value => 'land' %>  
  </div>


  <div class="field">
    <%= f.label :for %>
    <%= f.select :stype, [['Sell','sell'],['Rent','rent']] %>
  </div>

  <div class="field">
    <%= f.label :area %><br>
    <%= f.number_field :area %>
  </div>

  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_field :feature %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, min:'0', :required => true %>
  </div>


   <%= render :partial => "mapshow", :locals=>{:f=>f} %>



  <div class="actions">
    <%= f.submit :'Submit' %>
  </div>

<% end %>

app/views/estates/_mapshow.html.erb
<script type="text/javascript">
  function initialize() {
  var mapOptions = {

    <% if @c_lat.present? && @c_lng.present? %>
    center: new google.maps.LatLng(<%= @c_lat%>,<%= @c_lng %>),
    <% else %>
    center: new google.maps.LatLng(22.695800, 75.863557),
    <% end %>
    zoom: 14
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(
      document.getElementById('pac-input'));

  var types = document.getElementById('type-selector');
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(types);

  var autocomplete = new google.maps.places.Autocomplete(input);
  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map,
    draggable:true,
    anchorPoint: new google.maps.Point(0, -29)
  });

// additional

function geocodePosition(pos) 
{
   geocoder = new google.maps.Geocoder();
   geocoder.geocode
    ({
        latLng: pos
    }, 
        function(results, status) 
        {
            if (status == google.maps.GeocoderStatus.OK) 
            {
                $("#pac-input").val(results[0].formatted_address);
                $("#mapErrorMsg").hide(100);
            } 
            else 
            {
                $("#mapErrorMsg").html('Cannot determine address at this location.'+status).show(100);
            }
        }
    );
}

// end additional  










google.maps.event.addListener(marker, 'drag', function(evt){
   document.getElementById('latbox').value = evt.latLng.lat() ;
   document.getElementById('lngbox').value = evt.latLng.lng() ;
 });


google.maps.event.addListener(marker, 'drag', function(evt){
   geocodePosition(marker.getPosition());
 });




  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
//    marker.setIcon(/** @type {google.maps.Icon} */({
//      url: place.icon,
//      size: new google.maps.Size(71, 71),
//      origin: new google.maps.Point(0, 0),
//      anchor: new google.maps.Point(17, 34),
//      scaledSize: new google.maps.Size(35, 35)
//    }));

    marker.setPosition(place.geometry.location);
    document.getElementById('latbox').value = place.geometry.location.lat() ;
    document.getElementById('lngbox').value = place.geometry.location.lng() ;
    marker.setVisible(true);
    

    var address = '';
//    if (place.address_components) {
//      address = [
//        (place.address_components[0] && place.address_components[0].short_name || ''),
//        (place.address_components[1] && place.address_components[1].short_name || ''),
//        (place.address_components[2] && place.address_components[2].short_name || ''),
//        (place.address_components[3] && place.address_components[2].short_name || ''),
//        (place.address_components[4] && place.address_components[2].short_name || ''),
//      ].join(' ');
//    }

//    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
//    infowindow.open(map, marker);
  });

  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
   });
  }

  setupClickListener('changetype-all', []);
  
}

google.maps.event.addDomListener(window, 'load', initialize);

</script>
<% flag = 1 %>
     <%= f.fields_for :pictures do |p| %>
     <% if flag == 1 %>

     <div class="field">
       <%= p.label :avatar %><br>
       <%= p.file_field :avatar, :multiple => true, :required => true, name: "pictures[avatar][]" %>
  
  <!-- for caching -->
  <%= p.hidden_field :avatar_cache %>

  <%= p.hidden_field :_destroy %>


     </div>

    <% flag+=1 %>
   <% end %>
 <% end %>
  <div class="field">
    
    <%= f.text_field :address, :id=>"pac-input",:class=>"controls", :placeholder =>"Enter a location" %>
  </div>

  <div class="field">
    <%= f.label :"Latitude"%><br>
    <%= f.text_field :latitude, :id=>"latbox", :readonly => true,  :required => true %>
  </div>

  <div class="field">
    <%= f.label :"Longitude"%><br>
    <%= f.text_field :longitude, :id=>"lngbox", :readonly => true,  :required => true %>
  </div>

  <div id="type-selector" class="controls">
     
  </div>     
  <div id="map-canvas" style="height:400px;width:600px;"></div>

  

app/views/estates/edit.html.erb
<h1>Editing your post</h1>

<% if @type =="villa" %>
<%= render 'villa' %>

<% elsif @type =="flat" %>
<%= render 'flat' %>

<% elsif @type =="appartment" %>
<%= render 'appartment' %>

<% elsif @type =="land" %>
<%= render 'land' %>
<% end %>


<%= link_to 'Show', @estate,  'data-no-turbolink' => true %> |
<%= link_to 'See all property', estates_path %>

app/views/estates/index.html.erb
<div class="index_body">
      <div class="column1">

          <div class="left_box">
              <div class="top_left_box">
                </div>
                <div class="center_left_box">
                
                <div class='index_search'>
                 <%= render 'indexSearch'%> 
                </div>



                </div>

            </div>
            
            
 
          <div class="left_box">
              <div class="top_left_box">
                </div>
                <div class="center_left_box">
                  <div class="box_title"><span>Join</span> our newsletter:</div>
                    
                    
                    <div class="form">
                    <div class="form_row"><label class="left">Email: </label><input type="text" class="form_input"/></div>                    
                    <div style="float:right; padding:10px 25px 0 0;">
                    <input type="image" src="images/join.gif"/>
                    </div>
                    
                    </div>
                
                
                </div>
                <div class="bottom_left_box">
                </div>
            </div> 
 
 
          <div class="left_box">
              <div class="top_left_box">
                </div>
                <div class="center_left_box">
                  <div class="box_title"><span>Contact</span> information:</div>
                    
                    
                    <div class="form">
                    <div class="form_row">
                      <img src="images/contact_envelope.gif" width="50" height="47" border="0" class="img_right" alt="" title="" />
                        <div class="contact_information">
                        Email: info@comapnyname.com<br />
                        Telephone: 0234 789 90<br />
                        Mobile:      234 345 234534<br />
                        Fax:         34534 3456 3456(54)<br /><br />
                        
                        <span>www.companyname.com</span>
                        </div>
                    </div>                    
                    </div>
                
                
                </div>
                <div class="bottom_left_box">
                </div>
            </div>  
 
        
        </div><!-- end of column one -->
   





    <div class="column4">


     


    <div class="show_property">    
<h1 id="start_index">Properties</h1>
    <% @estates.each do |estate| %>
    <div class="main">
        <% @pictures = estate.pictures.all %> 
        <div class="property_pic">     
           <ul class="index_bxslider">
            <% @pictures.each do |p|%>
              <li><%= image_tag p.avatar_url(:thumb), class:"index_pic_size"%></li>
            <% end %>
            </ul>
            

             
 <%= link_to 'Show', estate, 'data-no-turbolink' => true %>
 <% if current_user.present? && estate.user_id == current_user.id  %> 
 <%= link_to 'Edit', edit_estate_path(estate), 'data-no-turbolink' => true %> 
      <% end %>
      </div>

    <div class="index_property_content">
      <table class="pdetail">
        <tr>
          <td>Types
          </td>
          <td>:<%= estate.ptype.titleize %></td>
        </tr>
        <tr><td>For</td><td>: <%= estate.stype %></td></tr>
        <% if estate.ptype =="villa"%>
        <tr>
          <td>Total floor</td>
          <td>: <%= estate.levels %></td>
        </tr>
        <% end %>
        <tr>
          <td class="item1">Area</td>
          <td>: <%= estate.area %></td>
        </tr>

        <% unless estate.ptype =="land" %>
        <tr>
          <td class="item1">Bedrooms</td>
          <td>: <%= estate.bedroom %></td>
        </tr><% end %>
        <% unless estate.ptype =="land" %>
        <tr>
          <td class="item1">Halls</td>
          <td>:<%= estate.hall %></td>
        </tr>
        <% end %>
        <% unless estate.ptype =="land" %>
        <tr>
          <td class="item1">Bathrooms</td>:
          <td>: <%= estate.bathroom %></td>
        </tr>
        <% end %>
        <tr>
          <td class="item1">Price</td>
          <td>: <%= estate.price %></td>
        </tr>
        <tr>
          <td class="item1">Owner</td>
          <td>:<%= User.find(estate.user_id).fname %> <%= User.find(estate.user_id).lname %></td>
        </tr>

        <tr>
          <td class="item1">Address </td>
          <td>: <%= estate.address %></td>
        </tr>
        </table>

      </div>
    </div>   

 
    <% end %>
</div>
<div class="pagination pagination-centered">
 <%= will_paginate @estates, renderer: BootstrapPagination::Rails %>
</div>
</div>

</div>

<script>    
  $(document).ready(function(){
  slider = $('.index_bxslider').bxSlider(
    {
  auto: true,
  autoControls: true,
  easing: 'ease-out'
}
    );
 
});
</script>

app/views/estates/new.html.erb
<div class="abody">
<h1>Publish your property</h1>

<% if params[:ptype]== 'villa' %>
<div class="dis" id =villa><%= render 'villa' %><hr> </div>
<% elsif params[:ptype]== 'flat' %>
<div class="dis" id =flat><%= render 'flat' %><hr> </div>
<% elsif params[:ptype]== 'appartment' %>
<div class="dis" id =appartment ><%= render 'appartment' %><hr></div> 
<% elsif params[:ptype]== 'land' %>
<div class="dis" id =land > <%= render 'land' %> <hr></div> 
<% end %>
<%= link_to 'Back', estates_path %>
</div>

app/views/estates/show.html.erb
<% content_for :head do %>
  
  <style>
#map-canvas {
        height: 100%;
        min-height: 300px;

      }

    </style>


    <script>
function initialize() {
  
  var mapOptions = {
    scrollwheel: false,
    center: new google.maps.LatLng(<%= @estate.latitude %>, <%= @estate.longitude %>),
    zoom: 18,
    mapTypeId: google.maps.MapTypeId.SATELLITE,
    heading: 90,
    tilt: 45
  };

  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  var marker = new google.maps.Marker({
    position: map.getCenter(),
    map: map,
    title: 'Click to zoom'
  });

  google.maps.event.addListener(map, 'center_changed', function() {
    // 3 seconds after the center of the map has changed, pan back to the
    // marker.
    window.setTimeout(function() {
      map.panTo(marker.getPosition());
    }, 30000);
  });
  var i = 12  ;
  google.maps.event.addListener(marker, 'click', function() {
    
    map.setZoom(i);
    i = i+3;
    map.setCenter(marker.getPosition());
  });
}

function rotate90() {
  var heading = map.getHeading() || 0;
  map.setHeading(heading + 90);
}

function autoRotate() {
  // Determine if we're showing aerial imagery
  if (map.getTilt() != 0) {
    window.setInterval(rotate90, 300);
  }
}


google.maps.event.addDomListener(window, 'load', initialize);

    </script>

<% end %>



<div class="showimage">            
<ul class="bxslider">

            <% @pictures.each do |p| %>

            
            <li>    
              <%= image_tag p.avatar_url, class:'showimage'%>
            </li>
            <% end %>
</ul>
</div>
<br>
<br>
<div class="show_page">

<p>
  <strong>Types of Property:</strong>
  <%= @estate.ptype %>

</p>

<p>
  <strong>Available for:</strong>
  <%= @estate.stype %>
</p>

<% unless @estate.ptype =="flat"%>
<% unless @estate.ptype =="appartment" %>
<% unless @estate.ptype =="land" %>
<p>
  <strong>Levels:</strong>
  <%= @estate.levels %>
</p>
<% end %>
<% end %>
<% end %>

<p>
  <strong>Area in squire meter:</strong>
  <%= @estate.area %>
</p>

<% unless @estate.ptype =="land" %>
<p>
  <strong>Bedroom:</strong>
  <%= @estate.bedroom %>
</p>
<% end %>

<% unless @estate.ptype =="land" %>
<p>
  <strong>Hall:</strong>
  <%= @estate.hall %>
</p>
<% end %>

<% unless @estate.ptype =="land" %>
<p>
  <strong>Bathroom:</strong>
  <%= @estate.bathroom %>
</p>
<% end %>

<% unless @estate.ptype =="land" %>
<p>
  <strong>Date of built:</strong>
  <%= @estate.built %>
</p>
<% end %>

<p>
  <strong>Address:</strong>
  <%= @estate.address %>
</p>



<p>
  <strong>Description</strong>
  <%= @estate.feature %>
</p>



<p>
  <strong>Price:</strong>
  <%= @estate.price %>
</p>

<% javascript_tag do %>
      var lat = <%= @estate.latitude %>
      var lat = <%= @estate.longitude %>
<% end %>
<p>
  <strong>Posted by:</strong>
  <%= User.find(@estate.user_id).fname %> <%= User.find(@estate.user_id).lname %>
</p>

<% if current_user.present? && current_user.id == @estate.user_id %><%= link_to 'Edit', edit_estate_path(@estate), 'data-no-turbolink' => true %> |

 <span class="item"><%= link_to 'delete', @estate, method: :delete, data: { confirm: 'Your post will be deleted. Contineu.. ?' } %> </span>
 <% end %> 
<%= link_to 'See all Property', estates_path %>


</div>

<div id="map-canvas" class="show_page"></div>


<script>    
  $(document).ready(function(){
  slider = $('.bxslider').bxSlider(
    {
  auto: true,
  autoControls: true,
  speed: 1000,
  easing: 'ease-out'

}
    );
 
});
</script>